import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const results=[],errors=[];
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:1050},extraHTTPHeaders:{'x-preview-user':`browser-test-${Date.now()}`}});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message});await page.screenshot({path:'tests/browser-failure.png',fullPage:true});throw e;}}
const nav=async name=>{await page.locator('[data-slot="sidebar-menu-button"]').filter({hasText:name}).click();await page.getByRole('heading',{name:name==='学习工作台'?'今天，从一篇好公文开始':name,exact:true}).waitFor();};
try{
await test('桌面首页加载，显示真实空档案和任务',async()=>{await page.goto('http://127.0.0.1:5173/');await page.getByRole('heading',{name:'今天，从一篇好公文开始'}).waitFor();await page.screenshot({path:'tests/desktop-home.png',fullPage:true});});
await test('知识库检索与空结果',async()=>{await nav('知识与素材');await page.getByRole('textbox',{name:'搜索知识素材'}).fill('没有这样的素材xyz');await page.getByText('没有匹配的资源，试试其他关键词或筛选条件。').waitFor();await page.getByRole('textbox',{name:'搜索知识素材'}).fill('');});
await test('病文分类与详情弹窗',async()=>{await page.getByRole('tab',{name:'病文',exact:true}).click();await page.getByRole('button',{name:/文种误用/}).click();await page.getByRole('dialog').getByText(/错误分析/).waitFor();await page.keyboard.press('Escape');});
await test('写作工作台打开，三栏可操作',async()=>{await nav('情景实训');await page.getByRole('button',{name:'开始 / 继续写作'}).first().click();await page.getByRole('textbox',{name:'公文正文'}).waitFor();});
const content='关于开展调查的报告\n办公室：\n大家赶紧把材料弄好，尽快报送检查情况。请批准新增经费。本次走访发现排水口堵塞，需要进行清理。下一步将建立巡查机制。';
await test('输入正文后自动保存',async()=>{await page.getByRole('textbox',{name:'公文正文'}).fill(content);await page.getByRole('main').getByText('草稿已保存',{exact:true}).waitFor();});
await test('离开后重进可恢复草稿',async()=>{await nav('情景实训');await page.getByRole('button',{name:'开始 / 继续写作'}).first().click();assert.equal(await page.getByRole('textbox',{name:'公文正文'}).inputValue(),content);});
await test('规则批注定位及采纳替换',async()=>{await page.getByRole('button',{name:'写作自查',exact:true}).click();await page.getByRole('button',{name:'采纳建议'}).first().waitFor();await page.getByRole('button',{name:'“大家”',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:'公文正文'}).evaluate(e=>e.value.substring(e.selectionStart,e.selectionEnd)),'大家');await page.getByRole('button',{name:'采纳建议'}).first().click();assert.ok((await page.getByRole('textbox',{name:'公文正文'}).inputValue()).includes('各有关单位'));});
await test('版式预览与返回编辑保留内容',async()=>{await page.getByRole('button',{name:'版式预览',exact:true}).click();await page.getByText('教学版式预览 · 不作为国标排版验收').waitFor();await page.getByRole('button',{name:'返回编辑',exact:true}).click();assert.ok((await page.getByRole('textbox',{name:'公文正文'}).inputValue()).includes('各有关单位'));});
await test('分级引导三步展开',async()=>{await page.getByRole('tab',{name:'引导',exact:true}).click();for(let i=0;i<3;i++)await page.getByRole('button',{name:'给我下一步提示'}).click();assert.equal(await page.getByRole('button',{name:'已展示全部提示'}).isDisabled(),true);await page.screenshot({path:'tests/desktop-editor.png',fullPage:true});});
await test('提交作业进入档案',async()=>{await page.getByRole('button',{name:'提交作业',exact:true}).click();await page.getByRole('button',{name:'确认提交',exact:true}).click();await page.getByRole('heading',{name:'学习档案',exact:true}).waitFor();await page.getByRole('button',{name:'反馈与原稿'}).waitFor();});
await test('教师退回重做，学生看到评语',async()=>{await nav('教师中心');await page.getByRole('button',{name:'复核 / 精批'}).first().click();await page.getByRole('textbox',{name:'教师评语'}).fill('请补充日期，删除请示事项，完善材料依据。');await page.getByRole('button',{name:'退回重做'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await nav('学习档案');await page.getByRole('button',{name:'反馈与原稿'}).first().click();await page.getByText('请补充日期，删除请示事项，完善材料依据。',{exact:true}).waitFor();});
await test('修改重交保留两个独立版本',async()=>{await page.getByRole('button',{name:'修改并再次提交'}).click();await page.getByRole('textbox',{name:'公文正文'}).fill(content+'\n2026年9月24日');await page.getByRole('button',{name:'提交作业',exact:true}).click();await page.getByRole('button',{name:'确认提交',exact:true}).click();await page.getByRole('heading',{name:'学习档案',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'反馈与原稿'}).count(),2);});
await test('教师填写五维分数并保存复核',async()=>{await nav('教师中心');await page.getByRole('button',{name:'复核 / 精批'}).first().click();for(const d of ['格式规范','文种与行文','结构与逻辑','语言表达','内容质量'])await page.getByRole('spinbutton',{name:d+'评分',exact:true}).fill('16');await page.getByRole('textbox',{name:'教师评语'}).fill('本次结构较完整，继续加强事实与建议的对应关系。');await page.getByRole('button',{name:'保存复核结果'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});});
await test('旧版本可补评并形成同任务成绩曲线',async()=>{await page.getByRole('button',{name:'复核 / 精批'}).nth(1).click();for(const d of ['格式规范','文种与行文','结构与逻辑','语言表达','内容质量'])await page.getByRole('spinbutton',{name:d+'评分',exact:true}).fill('14');await page.getByRole('textbox',{name:'教师评语'}).fill('初稿需要改进，补记初稿评分用于比较。');await page.getByRole('button',{name:'保存复核结果'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await nav('学习档案');await page.getByRole('img',{name:/同一任务历次成绩/}).waitFor();});
await test('学习档案展示评分和推荐练习',async()=>{await nav('学习档案');await page.getByText('80 分',{exact:true}).waitFor();await page.getByRole('button',{name:'去做针对性练习'}).waitFor();await page.screenshot({path:'tests/desktop-archive.png',fullPage:true});});
await test('阶段报告实际下载',async()=>{const promise=page.waitForEvent('download');await page.getByRole('button',{name:'导出阶段报告'}).click();const dl=await promise;assert.equal(dl.suggestedFilename(),'阶段性学习报告.txt');await dl.saveAs('tests/exported-report.txt');});
await test('客观题答错和正确反馈均可显示',async()=>{await nav('自主练习');await page.getByRole('radio',{name:'A 正确',exact:true}).click();await page.getByRole('button',{name:'提交答案'}).click();await page.getByText('还可以再想一想',{exact:true}).waitFor();await page.getByRole('radio',{name:'B 错误',exact:true}).click();await page.getByRole('button',{name:'提交答案'}).click();await page.getByText('回答正确',{exact:true}).waitFor();});
await test('教师发布任务表单可提交并展示',async()=>{await nav('教师中心');await page.getByRole('button',{name:'发布任务',exact:true}).click();await page.getByRole('textbox',{name:'任务名称',exact:true}).fill('浏览器测试：会议通知');await page.getByRole('textbox',{name:'情景背景与身份材料'}).fill('你是办公室工作人员，请组织一次工作会议，具体时间根据材料确定。');await page.getByRole('textbox',{name:'写作要求'}).fill('说明参会对象、时间和地点，不编造事实。');await page.getByRole('button',{name:'发布到我的班级'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('tab',{name:'已发布任务'}).click();await page.getByText('浏览器测试：会议通知',{exact:true}).waitFor();});
await test('资源文件上传保存后可检索',async()=>{await page.getByRole('button',{name:'共建资源'}).click();await page.locator('input[type=file]').setInputFiles({name:'浏览器测试范文.txt',mimeType:'text/plain',buffer:Buffer.from('【教学范文】各部门：请于指定日期前报送检查情况。批注：执行要求需明确。')});await page.getByRole('button',{name:'保存资源'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await nav('知识与素材');await page.getByRole('tab',{name:'全部',exact:true}).click();await page.getByRole('textbox',{name:'搜索知识素材'}).fill('浏览器测试范文');await page.getByRole('heading',{name:'浏览器测试范文',exact:true}).waitFor();});
await test('刷新保留数据库记录',async()=>{await page.reload();await page.getByRole('heading',{name:'今天，从一篇好公文开始'}).waitFor();await nav('学习档案');assert.equal(await page.getByRole('button',{name:'反馈与原稿'}).count(),2);});
await test('390px手机视图无整页横向溢出',async()=>{await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('heading',{name:'今天，从一篇好公文开始'}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:'tests/mobile-home.png',fullPage:true});});
await test('移动端侧栏可打开并导航',async()=>{await page.getByRole('button',{name:'Toggle Sidebar'}).click();await page.getByRole('button',{name:'情景实训',exact:true}).click();await page.keyboard.press('Escape');await page.getByRole('heading',{name:'情景实训',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:'tests/mobile-tasks.png',fullPage:true});});
await test('手机写作界面无横向溢出且可编辑',async()=>{await page.getByRole('button',{name:'开始 / 继续写作'}).first().click();await page.getByRole('textbox',{name:'公文正文'}).fill('关于会议安排的通知\n各部门：请核实会议时间地点后报送人员名单。');await page.getByRole('main').getByText('草稿已保存',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:'tests/mobile-editor.png',fullPage:true});});
await test('保存服务失败时保留正文并允许重试',async()=>{await page.route('**/api/lab',async route=>{if(route.request().method()==='POST')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'测试：保存服务暂不可用'})});else await route.continue();});const text='断网测试正文：请保留用户输入，在保存恢复后再次提交。';await page.getByRole('textbox',{name:'公文正文'}).fill(text);await page.getByText('保存失败，请重试',{exact:true}).waitFor();assert.equal(await page.getByRole('textbox',{name:'公文正文'}).inputValue(),text);await page.unroute('**/api/lab');await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('main').getByText('草稿已保存',{exact:true}).waitFor();});
await test('全过程无浏览器运行时异常',async()=>assert.deepEqual(errors,[]));
}finally{writeFileSync('tests/browser-results.json',JSON.stringify({time:new Date().toISOString(),results,errors},null,2));await browser.close();}

