'use client';
import {useState,useEffect,useRef,forwardRef,useImperativeHandle} from 'react';
import {Lightbulb,FileText,ChevronLeft,ChevronRight,CheckCheck,Save,Send,Eye,Download,Sparkles,MessageCircle,WandSparkles,RotateCcw,Trash2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {dimensions,knowledge,library} from '@/lib/content';
import type {Issue} from '@/lib/review';
import {api,Tag,Blank,download,R} from './ui';
export type EditorHandle={save:()=>Promise<void>};
const Editor=forwardRef<EditorHandle,{task:R;initial:string;back:()=>void;submitted:()=>void;detail:(r:R)=>void}>(function Editor({task,initial,back,submitted,detail},ref){
const [body,setBody]=useState(initial),[saved,setSaved]=useState(initial?'已恢复草稿':'新建草稿'),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[report,setReport]=useState<R|null>(null),[tab,setTab]=useState('规范要点'),[ignored,setIgnored]=useState<string[]>([]),[confirm,setConfirm]=useState(false),[guideMessages,setGuideMessages]=useState<R[]>([]),[guideInput,setGuideInput]=useState(''),[guideBusy,setGuideBusy]=useState(false),[guideLoaded,setGuideLoaded]=useState(false),[rewriteOpen,setRewriteOpen]=useState(false),[rewriteMode,setRewriteMode]=useState('formal'),[rewriteBusy,setRewriteBusy]=useState(false),[rewriteResult,setRewriteResult]=useState<R|null>(null),[selection,setSelection]=useState<R|null>(null),[undoBody,setUndoBody]=useState<string|null>(null);
const textRef=useRef<HTMLTextAreaElement>(null),bodyRef=useRef(initial),savedRef=useRef(initial),chain=useRef(Promise.resolve()),submissionId=useRef(''),selectionRef=useRef({start:0,end:0});
async function save(){const text=bodyRef.current;if(text===savedRef.current)return;setSaved('正在保存…');const run=chain.current.catch(()=>{}).then(async()=>{await api({action:'draft',task:task.id,content:text});savedRef.current=text;setSaved(bodyRef.current===text?'草稿已保存':'有未保存修改');});chain.current=run;try{await run;}catch(e){setSaved('保存失败，请重试');throw e;}}
useImperativeHandle(ref,()=>({save}));
useEffect(()=>{const timer=setTimeout(()=>save().catch(e=>toast.error(e.message)),1000);return()=>clearTimeout(timer);},[body]);
useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(bodyRef.current!==savedRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[]);
useEffect(()=>{if(tab!=='结构引导'||guideLoaded)return;setGuideLoaded(true);api({action:'aiGuideHistory',task:task.id}).then(r=>setGuideMessages(r.messages||[])).catch(e=>toast.error(e.message));},[tab,guideLoaded,task.id]);
function edit(text:string){bodyRef.current=text;setBody(text);setSaved('有未保存修改');setReport(null);submissionId.current='';}
async function check(){setBusy(true);try{setReport(await api({action:'check',task:task.id,content:body}));setIgnored([]);setTab('批改反馈');toast.success('规则检查完成');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
async function aiCheck(){setBusy(true);try{setReport(await api({action:'aiCheck',task:task.id,content:body}));setIgnored([]);setTab('批改反馈');toast.success('AI 语义批改完成');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
async function sendGuide(text=guideInput){const message=text.trim();if(!message||guideBusy)return;setGuideBusy(true);setGuideInput('');const optimistic={id:'pending-'+Date.now(),role:'user',content:message,actions:[]};setGuideMessages(v=>[...v,optimistic]);try{const r=await api({action:'aiGuideMessage',task:task.id,message,content:body});setGuideMessages(v=>[...v.filter(x=>x.id!==optimistic.id),r.userMessage,r.assistantMessage]);}catch(e){setGuideMessages(v=>v.filter(x=>x.id!==optimistic.id));setGuideInput(message);toast.error((e as Error).message);}finally{setGuideBusy(false);}}
async function resetGuide(){try{await api({action:'aiGuideReset',task:task.id});setGuideMessages([]);toast.success('本任务的引导对话已清空');}catch(e){toast.error((e as Error).message);}}
function openRewrite(){if(preview){toast.error('请先返回编辑状态并选中文字。');return;}const el=textRef.current,liveStart=el?.selectionStart??0,liveEnd=el?.selectionEnd??0,start=liveEnd>liveStart?liveStart:selectionRef.current.start,end=liveEnd>liveStart?liveEnd:selectionRef.current.end,original=body.slice(start,end);if(original.trim().length<10){toast.error('请先在正文中选择至少 10 个字。');el?.focus();return;}if(original.length>3000){toast.error('单次润色最多选择 3000 字。');return;}setSelection({start,end,original});setRewriteResult(null);setRewriteOpen(true);}
async function runRewrite(){if(!selection)return;setRewriteBusy(true);try{setRewriteResult(await api({action:'aiRewrite',task:task.id,original:selection.original,mode:rewriteMode}));}catch(e){toast.error((e as Error).message);}finally{setRewriteBusy(false);}}
async function acceptRewrite(){if(!selection||!rewriteResult)return;if(body.slice(selection.start,selection.end)!==selection.original){toast.error('原文已变化，请重新选择后润色。');return;}const before=body;edit(body.slice(0,selection.start)+rewriteResult.revisedText+body.slice(selection.end));setUndoBody(before);setRewriteOpen(false);await api({action:'aiRewriteAccept',id:rewriteResult.id}).catch(()=>{});toast.success('已采纳润色，可在编辑器下方撤销');}
async function submit(){setBusy(true);try{await save();if(!submissionId.current)submissionId.current=crypto.randomUUID();await api({action:'submit',id:submissionId.current,task:task.id,content:body});toast.success('已提交，等待教师复核');setConfirm(false);submitted();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
function apply(i:Issue){if(!i.replacement)return;if(body.slice(i.start,i.end)!==i.quote){toast.error('原文已变化，请重新检查。');return;}edit(body.slice(0,i.start)+i.replacement+body.slice(i.end));toast.success('已替换，请重新检查其他问题');}
return <><div className="editor-heading"><button className="text-btn" onClick={back}><ChevronLeft size={17}/>实训任务</button><h1>{task.title}</h1><div className="row"><span className="save-status">{saved}</span><button className="btn secondary" onClick={()=>save().then(()=>toast.success('草稿已保存')).catch(e=>toast.error(e.message))}><Save size={16}/>保存</button><button className="btn" disabled={busy} onClick={()=>setConfirm(true)}><Send size={16}/>提交作业</button></div></div><div className="workflow"><span className="active">01 理解情景</span><ChevronRight size={14}/><span className="active">02 起草与自查</span><ChevronRight size={14}/><span>03 提交与修改</span><ChevronRight size={14}/><span>04 教师复核</span></div>
<div className="workspace"><aside className="material-pane"><Tag>{task.genre} · {task.level}</Tag><h3>情景材料</h3><p>{task.background}</p><h3>写作要求</h3><p>{task.requirements}</p><h3>评分量规</h3>{dimensions.map((d,i)=><div className="rubric-row" key={d}><span>{d}</span><b>{task.rubric[i]} 分</b></div>)}<small className="muted">本任务为教学情景。事实与政策引用需要核实。</small></aside><section className="paper-pane"><div className="editor-toolbar"><span>正文编辑 <small>{body.replace(/\s/g,'').length} 字</small></span><div className="row"><button className="text-btn" onClick={()=>setPreview(!preview)}><Eye size={15}/>{preview?'返回编辑':'版式预览'}</button><button className="text-btn ai-button" disabled={busy||preview} onClick={openRewrite}><WandSparkles size={16}/>AI 润色</button><button className="text-btn" disabled={busy} onClick={check}><CheckCheck size={16}/>规则自查</button><button className="text-btn ai-button" disabled={busy} onClick={aiCheck}><Sparkles size={16}/>{busy?'处理中…':'AI 语义批改'}</button></div></div>{preview?<div className="paper-preview"><div className="preview-note">教学版式预览 · 不作为国标排版验收</div><div className="paper-text">{body||'正文为空'}</div></div>:<textarea ref={textRef} className="writing-area" aria-label="公文正文" placeholder={'在这里开始你的写作…\n\n建议先写标题，再逐项整理事实、分析与要求。'} maxLength={20000} value={body} onChange={e=>edit(e.target.value)} onSelect={e=>{selectionRef.current={start:e.currentTarget.selectionStart,end:e.currentTarget.selectionEnd}}}/>}<div className="editor-bottom"><span>段落编辑 · 最多 20,000 字</span><div className="row">{undoBody!==null&&<button className="text-btn" onClick={()=>{edit(undoBody);setUndoBody(null);toast.success('已撤销 AI 润色')}}><RotateCcw size={14}/>撤销润色</button>}<button className="text-btn" onClick={()=>download(task.title+'.txt',body)}><Download size={14}/>导出正文</button></div></div></section>
<aside className="assistant-pane"><h3><Lightbulb size={18}/> 写作助手</h3><Tabs value={tab} onValueChange={setTab}><TabsList className="assist-tabs"><TabsTrigger value="规范要点">规范</TabsTrigger><TabsTrigger value="结构引导">引导</TabsTrigger><TabsTrigger value="批改反馈">批改</TabsTrigger></TabsList><TabsContent value="规范要点"><h4>{task.genre}写作要点</h4><p>{knowledge.find(k=>k.genre===task.genre)?.tips}</p><div className="mini-card"><b>结构参考</b><p>{knowledge.find(k=>k.genre===task.genre)?.outline}</p></div><h4>相关素材</h4>{library.filter(r=>r.genre===task.genre||r.category==='金句').map(r=><button className="resource-link" key={r.id} onClick={()=>detail(r)}><FileText size={15}/>{r.title}<ChevronRight size={14}/></button>)}<p className="muted small">范文用于理解结构，事实不可直接套用。</p></TabsContent>
<TabsContent value="结构引导"><div className="guide-head"><Tag color="amber-tag">AI 引导 · 不代写全文</Tag>{guideMessages.length>0&&<button className="text-btn muted" onClick={resetGuide}><Trash2 size={13}/>清空</button>}</div><h4>先厘清，再下笔</h4>{!guideMessages.length&&<><p>AI会结合本题材料和当前正文，通过提问帮助你梳理写作对象、事实与结构。</p><div className="guide-starters">{['帮我厘清行文对象和目的','帮我区分已知事实与待核实信息','根据要求帮我搭建结构'].map(x=><button key={x} onClick={()=>sendGuide(x)}>{x}</button>)}</div></>}<div className="guide-messages">{guideMessages.map(m=><div className={`guide-message ${m.role}`} key={m.id}><b>{m.role==='user'?'我':'写作助手'}</b><p>{m.content}</p>{m.role==='assistant'&&m.actions?.length>0&&<div className="guide-actions">{m.actions.map((x:string)=><button key={x} disabled={guideBusy} onClick={()=>sendGuide(x)}>{x}</button>)}</div>}</div>)}{guideBusy&&<div className="guide-message assistant"><b>写作助手</b><p>正在结合材料思考…</p></div>}</div><div className="guide-compose"><textarea aria-label="向写作助手提问" maxLength={1000} value={guideInput} onChange={e=>setGuideInput(e.target.value)} placeholder="描述你卡住的地方…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendGuide();}}}/><button className="btn" disabled={guideBusy||!guideInput.trim()} onClick={()=>sendGuide()}><MessageCircle size={15}/>发送</button></div><p className="muted small">AI只提供分步提示，事实和政策仍需核实。每日最多20次。</p></TabsContent>
<TabsContent value="批改反馈"><div className="notice">{report?.mode==='ai'?'AI 评分仅供学习参考，最终成绩以教师复核为准。':'规则检查不产生分数；内容、政策和复杂逻辑由教师复核。'}</div>{report?<><p>{report.summary}</p>{report.scores&&<div className="ai-scores">{report.scores.map((s:R)=><div key={s.dimension}><span>{s.dimension}</span><b>{s.score}/{s.maxScore}</b><small>{s.reason}</small></div>)}</div>}{report.revisionPlan?.length>0&&<div className="mini-card"><b>建议修改顺序</b><ol>{report.revisionPlan.map((x:string)=><li key={x}>{x}</li>)}</ol></div>}{report.issues.map((i:Issue)=>!ignored.includes(i.id)&&<div className="issue-card" key={i.id}><Tag color="amber-tag">{dimensions[i.dimension]}</Tag>{i.quote&&<button className="quote" title={i.message+' '+i.suggestion} onClick={()=>{setPreview(false);setTimeout(()=>{textRef.current?.focus();textRef.current?.setSelectionRange(i.start,i.end);},0);}}>“{i.quote}”</button>}<p>{i.message}</p><small>{i.suggestion}</small><div className="row">{i.replacement&&<button className="text-btn" onClick={()=>apply(i)}>采纳建议</button>}<button className="text-btn muted" onClick={()=>setIgnored([...ignored,i.id])}>忽略本次提示</button></div></div>)}</>:<Blank text="选择规则自查或 AI 语义批改，查看反馈。"/>}</TabsContent></Tabs></aside></div>
<Dialog open={rewriteOpen} onOpenChange={v=>!rewriteBusy&&setRewriteOpen(v)}><DialogContent className="rewrite-dialog"><DialogHeader><DialogTitle>AI 选段润色</DialogTitle><DialogDescription>只处理选中文字；采纳前请核对事实、数字和责任主体。</DialogDescription></DialogHeader><label>润色目标<select className="field" value={rewriteMode} onChange={e=>{setRewriteMode(e.target.value);setRewriteResult(null)}}><option value="formal">正式公文表达</option><option value="concise">精简冗余内容</option><option value="logic">改善逻辑衔接</option><option value="proofread">仅改错字和病句</option></select></label><div className="rewrite-compare"><section><h4>原文</h4><div>{selection?.original}</div></section><section><h4>建议稿</h4><div>{rewriteResult?.revisedText||'点击“生成润色建议”后在此查看结果。'}</div></section></div>{rewriteResult&&rewriteResult.changes?.length>0&&<div className="rewrite-notes"><b>修改说明</b><ul>{rewriteResult.changes.map((x:R,i:number)=><li key={i}>{x.type}：{x.reason}</li>)}</ul>{rewriteResult.warnings?.map((x:string)=><p key={x}>注意：{x}</p>)}</div>}<div className="row rewrite-actions"><button className="btn secondary" disabled={rewriteBusy} onClick={runRewrite}>{rewriteBusy?'正在生成…':rewriteResult?'重新生成':'生成润色建议'}</button>{rewriteResult&&<button className="btn" disabled={rewriteBusy} onClick={acceptRewrite}>采纳并替换选中文字</button>}</div><p className="muted small">每日最多10次。系统会阻止加入原文没有的数字或日期。</p></DialogContent></Dialog><Dialog open={confirm} onOpenChange={v=>!busy&&setConfirm(v)}><DialogContent><DialogHeader><DialogTitle>提交本次作业</DialogTitle><DialogDescription>本次原稿将独立保存，后续修改不会覆盖旧版本。</DialogDescription></DialogHeader><p>正文共 {body.replace(/\s/g,'').length} 字。提交后等待教师复核；AI 建议分不会自动计入正式成绩。</p><button className="btn full" disabled={busy} onClick={submit}>{busy?'提交中…':'确认提交'}</button></DialogContent></Dialog></>;
});
export default Editor;
