'use client';
import {useState,useEffect,useRef,forwardRef,useImperativeHandle} from 'react';
import {Lightbulb,FileText,ChevronLeft,ChevronRight,CheckCheck,Save,Send,Eye,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {dimensions,knowledge,library} from '@/lib/content';
import type {Issue} from '@/lib/review';
import {api,Tag,Blank,download,R} from './ui';
export type EditorHandle={save:()=>Promise<void>};
const Editor=forwardRef<EditorHandle,{task:R;initial:string;back:()=>void;submitted:()=>void;detail:(r:R)=>void}>(function Editor({task,initial,back,submitted,detail},ref){
const [body,setBody]=useState(initial),[saved,setSaved]=useState(initial?'已恢复草稿':'新建草稿'),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[report,setReport]=useState<R|null>(null),[tab,setTab]=useState('规范要点'),[hint,setHint]=useState(0),[ignored,setIgnored]=useState<string[]>([]),[confirm,setConfirm]=useState(false);
const textRef=useRef<HTMLTextAreaElement>(null),bodyRef=useRef(initial),savedRef=useRef(initial),chain=useRef(Promise.resolve()),submissionId=useRef('');
async function save(){const text=bodyRef.current;if(text===savedRef.current)return;setSaved('正在保存…');const run=chain.current.catch(()=>{}).then(async()=>{await api({action:'draft',task:task.id,content:text});savedRef.current=text;setSaved(bodyRef.current===text?'草稿已保存':'有未保存修改');});chain.current=run;try{await run;}catch(e){setSaved('保存失败，请重试');throw e;}}
useImperativeHandle(ref,()=>({save}));
useEffect(()=>{const timer=setTimeout(()=>save().catch(e=>toast.error(e.message)),1000);return()=>clearTimeout(timer);},[body]);
useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(bodyRef.current!==savedRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[]);
function edit(text:string){bodyRef.current=text;setBody(text);setSaved('有未保存修改');setReport(null);submissionId.current='';}
async function check(){setBusy(true);try{setReport(await api({action:'check',task:task.id,content:body}));setIgnored([]);setTab('批改反馈');toast.success('规则检查完成');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
async function submit(){setBusy(true);try{await save();if(!submissionId.current)submissionId.current=crypto.randomUUID();await api({action:'submit',id:submissionId.current,task:task.id,content:body});toast.success('已提交，等待教师复核');setConfirm(false);submitted();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
function apply(i:Issue){if(!i.replacement)return;if(body.slice(i.start,i.end)!==i.quote){toast.error('原文已变化，请重新检查。');return;}edit(body.slice(0,i.start)+i.replacement+body.slice(i.end));toast.success('已替换，请重新检查其他问题');}
return <><div className="editor-heading"><button className="text-btn" onClick={back}><ChevronLeft size={17}/>实训任务</button><h1>{task.title}</h1><div className="row"><span className="save-status">{saved}</span><button className="btn secondary" onClick={()=>save().then(()=>toast.success('草稿已保存')).catch(e=>toast.error(e.message))}><Save size={16}/>保存</button><button className="btn" disabled={busy} onClick={()=>setConfirm(true)}><Send size={16}/>提交作业</button></div></div><div className="workflow"><span className="active">01 理解情景</span><ChevronRight size={14}/><span className="active">02 起草与自查</span><ChevronRight size={14}/><span>03 提交与修改</span><ChevronRight size={14}/><span>04 教师复核</span></div>
<div className="workspace"><aside className="material-pane"><Tag>{task.genre} · {task.level}</Tag><h3>情景材料</h3><p>{task.background}</p><h3>写作要求</h3><p>{task.requirements}</p><h3>评分量规</h3>{dimensions.map((d,i)=><div className="rubric-row" key={d}><span>{d}</span><b>{task.rubric[i]} 分</b></div>)}<small className="muted">本任务为教学情景。事实与政策引用需要核实。</small></aside><section className="paper-pane"><div className="editor-toolbar"><span>正文编辑 <small>{body.replace(/\s/g,'').length} 字</small></span><div className="row"><button className="text-btn" onClick={()=>setPreview(!preview)}><Eye size={15}/>{preview?'返回编辑':'版式预览'}</button><button className="text-btn" disabled={busy} onClick={check}><CheckCheck size={16}/>{busy?'处理中…':'写作自查'}</button></div></div>{preview?<div className="paper-preview"><div className="preview-note">教学版式预览 · 不作为国标排版验收</div><div className="paper-text">{body||'正文为空'}</div></div>:<textarea ref={textRef} className="writing-area" aria-label="公文正文" placeholder={'在这里开始你的写作…\n\n建议先写标题，再逐项整理事实、分析与要求。'} maxLength={20000} value={body} onChange={e=>edit(e.target.value)}/>}<div className="editor-bottom"><span>段落编辑 · 最多 20,000 字</span><button className="text-btn" onClick={()=>download(task.title+'.txt',body)}><Download size={14}/>导出正文</button></div></section>
<aside className="assistant-pane"><h3><Lightbulb size={18}/> 写作助手</h3><Tabs value={tab} onValueChange={setTab}><TabsList className="assist-tabs"><TabsTrigger value="规范要点">规范</TabsTrigger><TabsTrigger value="结构引导">引导</TabsTrigger><TabsTrigger value="批改反馈">批改</TabsTrigger></TabsList><TabsContent value="规范要点"><h4>{task.genre}写作要点</h4><p>{knowledge.find(k=>k.genre===task.genre)?.tips}</p><div className="mini-card"><b>结构参考</b><p>{knowledge.find(k=>k.genre===task.genre)?.outline}</p></div><h4>相关素材</h4>{library.filter(r=>r.genre===task.genre||r.category==='金句').map(r=><button className="resource-link" key={r.id} onClick={()=>detail(r)}><FileText size={15}/>{r.title}<ChevronRight size={14}/></button>)}<p className="muted small">范文用于理解结构，事实不可直接套用。</p></TabsContent>
<TabsContent value="结构引导"><Tag color="amber-tag">教学提示 · 非 AI 生成</Tag><h4>先厘清，再下笔</h4><p>收文对象是谁？你希望对方了解什么，或采取什么行动？</p>{hint>0&&<div className="mini-card"><b>第一步 · 整理事实</b><p>将材料分成“已知事实、存在问题、可行措施”三列。没有依据的数据单独标记。</p></div>}{hint>1&&<div className="mini-card"><b>第二步 · 搭建结构</b><p>{knowledge.find(k=>k.genre===task.genre)?.outline}</p></div>}{hint>2&&<div className="mini-card"><b>第三步 · 检查对应</b><p>每个判断是否有依据？建议是否回应问题？时间和责任是否具体？</p></div>}<button className="btn secondary full" disabled={hint>=3} onClick={()=>setHint(hint+1)}>{hint>=3?'已展示全部提示':'给我下一步提示'}</button><p className="muted small">AI 对话与自由润色将在模型服务接入后开放。</p></TabsContent>
<TabsContent value="批改反馈"><div className="notice">规则检查不产生 AI 分数；内容、政策和复杂逻辑由教师复核。</div>{report?<><p>{report.summary}</p>{report.issues.map((i:Issue)=>!ignored.includes(i.id)&&<div className="issue-card" key={i.id}><Tag color="amber-tag">{dimensions[i.dimension]}</Tag>{i.quote&&<button className="quote" title={i.message+' '+i.suggestion} onClick={()=>{setPreview(false);setTimeout(()=>{textRef.current?.focus();textRef.current?.setSelectionRange(i.start,i.end);},0);}}>“{i.quote}”</button>}<p>{i.message}</p><small>{i.suggestion}</small><div className="row">{i.replacement&&<button className="text-btn" onClick={()=>apply(i)}>采纳建议</button>}<button className="text-btn muted" onClick={()=>setIgnored([...ignored,i.id])}>忽略本次提示</button></div></div>)}</>:<Blank text="点击“写作自查”，查看规则提示。"/>}</TabsContent></Tabs></aside></div>
<Dialog open={confirm} onOpenChange={v=>!busy&&setConfirm(v)}><DialogContent><DialogHeader><DialogTitle>提交本次作业</DialogTitle><DialogDescription>本次原稿将独立保存，后续修改不会覆盖旧版本。</DialogDescription></DialogHeader><p>正文共 {body.replace(/\s/g,'').length} 字。提交后可查看规则提示，等待教师复核。</p><div className="notice">AI 语义批改尚未接入，本次不会生成 AI 五维评分。</div><button className="btn full" disabled={busy} onClick={submit}>{busy?'提交中…':'确认提交'}</button></DialogContent></Dialog></>;
});
export default Editor;
