import { env } from 'cloudflare:workers';
import { database } from '@/db/raw';
import { seedTasks, questions, genres } from '@/lib/content';
import { checkWriting, validateRubric, validateScores } from '@/lib/review';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
class HttpError extends Error {constructor(public status:number,message:string){super(message);}}
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
function identity(req:Request){const local=(env as any).LOCAL_PREVIEW==='true';const id=req.headers.get('oai-authenticated-user-id')||(local?(req.headers.get('x-preview-user')||'preview-owner'):null);if(!id)throw new HttpError(401,'请登录后使用学习空间。');return {id,name:req.headers.get('oai-authenticated-user-email')||(local?id:'学习者')};}
function str(v:unknown,label:string,max=20000){if(typeof v!=='string'||!v.trim()||v.length>max)throw new HttpError(400,`${label}不能为空，且不得超过 ${max} 字。`);return v.trim();}
const parse=(r:Row)=>({...r,...(r.rubric?{rubric:JSON.parse(r.rubric)}:{}),...(r.report?{report:JSON.parse(r.report)}:{}),...(r.scores?{scores:JSON.parse(r.scores)}:{})});
async function init(id:string,name:string){const db=database();const classroom=`class-${id}`;const existing=await db.prepare('SELECT id FROM classrooms WHERE id=?').bind(classroom).first();if(existing)return;
 const statements=[db.prepare('INSERT OR IGNORE INTO classrooms (id,owner,name,code) VALUES (?,?,?,?)').bind(classroom,id,'我的公文实训班',uid().replaceAll('-','').slice(0,12).toUpperCase()),db.prepare('INSERT OR IGNORE INTO members (id,classroom,user,name) VALUES (?,?,?,?)').bind(`${classroom}:${id}`,classroom,id,name)];
 seedTasks.forEach((t,i)=>statements.push(db.prepare('INSERT OR IGNORE INTO tasks (id,classroom,title,genre,background,requirements,deadline,rubric,level,created) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(`${classroom}-task-${i}`,classroom,t.title,t.genre,t.background,t.requirements,'',JSON.stringify([20,20,20,20,20]),t.level,now())));await db.batch(statements);}
async function getTask(id:unknown,user:string,owner=false){const db=database();const task=await db.prepare('SELECT t.*,c.owner FROM tasks t JOIN classrooms c ON c.id=t.classroom WHERE t.id=?').bind(str(id,'任务编号',200)).first<Row>();if(!task)throw new HttpError(404,'任务不存在。');if(owner){if(task.owner!==user)throw new HttpError(403,'只能管理自己班级的任务。');}else {const m=await db.prepare('SELECT id FROM members WHERE classroom=? AND user=?').bind(task.classroom,user).first();if(!m)throw new HttpError(403,'请先加入该班级。');}return task;}
async function ownerClass(classroom:unknown,user:string){const c=await database().prepare('SELECT * FROM classrooms WHERE id=? AND owner=?').bind(str(classroom,'班级',200),user).first<Row>();if(!c)throw new HttpError(403,'无权管理该班级。');return c;}
async function getData(id:string){const db=database();const [classes,tasks,drafts,submissions,resources,attempts,members]=await Promise.all([
 db.prepare('SELECT c.* FROM classrooms c JOIN members m ON m.classroom=c.id WHERE m.user=?').bind(id).all(),
 db.prepare('SELECT t.* FROM tasks t JOIN members m ON m.classroom=t.classroom WHERE m.user=? ORDER BY t.created DESC,t.id').bind(id).all(),
 db.prepare('SELECT * FROM drafts WHERE user=?').bind(id).all(),
 db.prepare('SELECT s.* FROM submissions s JOIN tasks t ON t.id=s.task JOIN classrooms c ON c.id=t.classroom WHERE s.user=? OR c.owner=? ORDER BY s.created DESC').bind(id,id).all(),
 db.prepare('SELECT r.* FROM resources r JOIN members m ON m.classroom=r.classroom WHERE m.user=? ORDER BY r.created DESC').bind(id).all(),
 db.prepare('SELECT * FROM attempts WHERE user=? ORDER BY created DESC').bind(id).all(),
 db.prepare('SELECT m.* FROM members m JOIN classrooms c ON c.id=m.classroom WHERE c.owner=?').bind(id).all()
 ]);return {user:id,classes:classes.results,tasks:tasks.results.map(parse),drafts:drafts.results,submissions:submissions.results.map(parse),resources:resources.results,attempts:attempts.results,members:members.results,aiReady:false};}
function error(e:unknown){console.error('lab-api',e instanceof Error?e.message:e);return Response.json({error:e instanceof Error?e.message:'服务暂时不可用'}, {status:e instanceof HttpError?e.status:500});}
export async function GET(req:Request){try{const u=identity(req);await init(u.id,u.name);return Response.json(await getData(u.id));}catch(e){return error(e);}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'请求来源不匹配。');
 const u=identity(req);if(Number(req.headers.get('content-length')||0)>150000)throw new HttpError(413,'提交内容过大。');const raw=await req.text();if(raw.length>100000)throw new HttpError(413,'提交内容过大。');let b:Row;try{b=JSON.parse(raw);}catch{throw new HttpError(400,'提交格式错误。');}if(!b||typeof b!=='object'||Array.isArray(b))throw new HttpError(400,'请求内容必须是对象。');await init(u.id,u.name);const db=database();
 if(b.action==='join'){const c=await db.prepare('SELECT * FROM classrooms WHERE code=?').bind(str(b.code,'班级码',30).toUpperCase()).first<Row>();if(!c)throw new HttpError(404,'班级码无效。');await db.prepare('INSERT OR IGNORE INTO members (id,classroom,user,name) VALUES (?,?,?,?)').bind(`${c.id}:${u.id}`,c.id,u.id,u.name).run();return Response.json({ok:true});}
 if(b.action==='task'){const c=await ownerClass(b.classroom,u.id);const title=str(b.title,'任务名称',120),genre=str(b.genre,'文种',20);if(!genres.includes(genre))throw new HttpError(400,'文种无效。');let rubric:number[];try{rubric=validateRubric(b.rubric);}catch(e){throw new HttpError(400,(e as Error).message);}const deadline=b.deadline?str(b.deadline,'截止日期',40):'';if(deadline&&(!Number.isFinite(Date.parse(deadline))||Date.parse(deadline)<Date.now()))throw new HttpError(400,'截止时间应晚于当前时间。');const id=uid();await db.prepare('INSERT INTO tasks (id,classroom,title,genre,background,requirements,deadline,rubric,level,created) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,c.id,title,genre,str(b.background,'情景材料'),str(b.requirements,'写作要求'),deadline,JSON.stringify(rubric),str(b.level,'难度',20),now()).run();return Response.json({ok:true,id});}
 if(['draft','check','submit'].includes(b.action)){const task=await getTask(b.task,u.id);if(typeof b.content!=='string'||b.content.length>20000)throw new HttpError(400,'正文不得超过 20000 字。');const content=b.content;const did=`${u.id}:${task.id}`;
 if(b.action==='draft'){await db.prepare('INSERT INTO drafts (id,user,task,content,updated) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content,updated=excluded.updated').bind(did,u.id,task.id,content,now()).run();return Response.json({ok:true,updated:now()});}
 if(content.trim().length<20)throw new HttpError(400,'请先完成至少 20 字的正文。');const report=checkWriting(content,task.genre);if(b.action==='check')return Response.json(report);
 if(task.deadline&&Date.now()>Date.parse(task.deadline))throw new HttpError(400,'任务已截止，草稿仍可保存。');const id=str(b.id,'提交编号',100);const previous=await db.prepare('SELECT user,task,content FROM submissions WHERE id=?').bind(id).first<Row>();if(previous){if(previous.user!==u.id||previous.task!==task.id||previous.content!==content)throw new HttpError(409,'提交编号冲突，请重新提交。');return Response.json({ok:true,id});}await db.batch([db.prepare('INSERT OR IGNORE INTO submissions (id,user,name,task,content,report,status,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,u.id,u.name,task.id,content,JSON.stringify(report),'submitted',now()),db.prepare('INSERT INTO drafts (id,user,task,content,updated) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content,updated=excluded.updated').bind(did,u.id,task.id,content,now())]);return Response.json({ok:true,id});}
 if(b.action==='review'){const s=await db.prepare('SELECT * FROM submissions WHERE id=?').bind(str(b.id,'作业编号',100)).first<Row>();if(!s)throw new HttpError(404,'作业不存在。');const task=await getTask(s.task,u.id,true);if(!['reviewed','returned'].includes(b.status))throw new HttpError(400,'状态无效。');let scores:number[]|null=null;if(b.status==='reviewed'){try{scores=validateScores(b.scores,JSON.parse(task.rubric));}catch(e){throw new HttpError(400,(e as Error).message);}}const comment=str(b.comment,'教师评语',5000);await db.prepare('UPDATE submissions SET status=?,scores=?,comment=?,reviewed=? WHERE id=?').bind(b.status,scores?JSON.stringify(scores):null,comment,now(),s.id).run();return Response.json({ok:true});}
 if(b.action==='resource'){const c=await ownerClass(b.classroom,u.id);const category=str(b.category,'资源类别',20);if(!['范文','病文','模板','金句','专题','任务'].includes(category))throw new HttpError(400,'资源类别无效。');await db.prepare('INSERT INTO resources (id,classroom,title,genre,category,industry,body,created) VALUES (?,?,?,?,?,?,?,?)').bind(uid(),c.id,str(b.title,'资源名称',120),str(b.genre,'文种',20),category,str(b.industry,'行业',40),str(b.body,'资源内容',30000),now()).run();return Response.json({ok:true});}
 if(b.action==='answer'){const q=questions.find(x=>x.id===b.question);if(!q)throw new HttpError(404,'题目不存在。');const answer=str(b.answer,'答案',500);const correct=answer===q.answer;await db.prepare('INSERT INTO attempts (id,user,question,answer,correct,created) VALUES (?,?,?,?,?,?)').bind(uid(),u.id,q.id,answer,correct?1:0,now()).run();return Response.json({correct,answer:q.answer,explain:q.explain});}
 throw new HttpError(400,'不支持的操作。');
 }catch(e){return error(e);}}

