// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const classrooms = sqliteTable('classrooms', { id: text('id').primaryKey(), owner: text('owner').notNull(), name: text('name').notNull(), code: text('code').notNull().unique() });
export const members = sqliteTable('members', { id: text('id').primaryKey(), classroom: text('classroom').notNull(), user: text('user').notNull(), name: text('name').notNull() }, t=>[index('idx_members_user').on(t.user)]);
export const tasks = sqliteTable('tasks', { id: text('id').primaryKey(), classroom: text('classroom').notNull(), title: text('title').notNull(), genre: text('genre').notNull(), background: text('background').notNull(), requirements: text('requirements').notNull(), deadline: text('deadline').notNull(), rubric: text('rubric').notNull(), level: text('level').notNull(), created: text('created').notNull() }, t=>[index('idx_tasks_classroom').on(t.classroom)]);
export const drafts = sqliteTable('drafts', { id: text('id').primaryKey(), user: text('user').notNull(), task: text('task').notNull(), content: text('content').notNull(), updated: text('updated').notNull() });
export const submissions = sqliteTable('submissions', { id: text('id').primaryKey(), user: text('user').notNull(), name: text('name').notNull(), task: text('task').notNull(), content: text('content').notNull(), report: text('report').notNull(), status: text('status').notNull(), scores: text('scores'), comment: text('comment'), created: text('created').notNull(), reviewed: text('reviewed') },t=>[index('idx_submissions_user').on(t.user),index('idx_submissions_task').on(t.task)]);
export const resources = sqliteTable('resources', { id:text('id').primaryKey(), classroom:text('classroom').notNull(), title:text('title').notNull(), genre:text('genre').notNull(), category:text('category').notNull(), industry:text('industry').notNull(), body:text('body').notNull(), created:text('created').notNull() });
export const attempts = sqliteTable('attempts', { id:text('id').primaryKey(), user:text('user').notNull(), question:text('question').notNull(), answer:text('answer').notNull(), correct:integer('correct').notNull(), created:text('created').notNull() },t=>[index('idx_attempts_user').on(t.user)]);
